#!/usr/bin/env bash
# Make sure that the script exits if Hadrian fails to build
set -euo pipefail
stack build --profile --ghc-options "-fprof-auto" hakyll:exe:hakyll-website
stack exec --profile -- hakyll-website +RTS -xc -RTS -- build

# stack ghci hakyll:lib hakyll:exe:hakyll-website --ghci-options "-fbreak-on-exception -fbreak-on-error"